server:
  port: 8081
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
    - text/html
    - text/xml
    - text/plain
    - text/css
    - text/javascript
    - application/javascript
    - application/json
    - application/xml
    - image/png
    - image/jpeg
    - image/jpg
spring:
  application:
    name: skill6-website
  datasource:
    username: ${SKILL6_MYSQL_USERNAME}
    password: ${SKILL6_MYSQL_PASSWROD}
    url: ${SKILL6_MYSQL_URL}
    druid:
      name: skill6-mysql-01
    schema: classpath*:schema/init_db.sql
    initialization-mode: always
  redis:
    host: ${SKILL6_REDIS_HOST}
    password: ${SKILL6_REDIS_PASSWORD}
    port: ${SKILL6_REDIS_PORT}
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
dubbo:
  application:
    name: user-rbac-provider
  registry:
    address: zookeeper://localhost:2181
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: cn.skill6.common.entity.po
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-enum-type-handler: cn.skill6.common.mybatis.GeneralStateFieldHandler
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    root: INFO
    cn.skill6.website.dao: DEBUG
    cn.skill6.website.config.SEOInterceptor: DEBUG
skill6:
  file-path: /skill6/file/
  image-path: /skill6/image/
  sequence:
    worker:
      id: 1
    data-center:
      id: 1
  recaptcha:
    secret-key: ${SKILL6_RECAPTCHA_SECRET_KEY}
    verify-url: https://www.recaptcha.net/recaptcha/api/siteverify
  github:
    client_id: gsasga241124
    client_secret: 1325dfd235dfs
  qq:
    client_id: 123
    redirect_uri: http://127.0.0.1/login/qq
    scope: get_user_info
    status: 124125
shiro:
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /unauthorized
  config-path: classpath:config/shiro-urls.ini